### ISSUE TITLE
Objects cant be viewed after git push and sso profile

### ISSUE THREAD

**Issue by andreprawira** [awslabs/git-remote-s3#13]
I was able to follow the instructions all the way until pushing my code to my s3 bucket but when i look at my bucket i dont see my codes only a .bundle file, here is the path `s3://<my-bucket-name>/<my-repo-name>/refs/heads/master/7a31b6.bundle` is this an expected behavior? 

On another note, anyway to clone using aws sso profile? I tried `git clone s3://<my-aws-sso-profile>@<my-bucket-name>` and `git clone s3://<my-bucket-name>@<my-aws-sso-profile>` both times i got this error `fatal: invalid remote. You need to have a bucket and a prefix.`

**Comment by massi-ang** [comment]
Hi Andre,

For your first question, this it the expected behavior. We use git bundles to store the git history and all the metadata in S3.

For your second question, the correct format is `s3://<my-aws-sso-profile>@<my-bucket-name>/<prefix>`. Do not forget the prefix.

**Comment by andreprawira** [comment]
@massi-ang forgive my english but what is prefix? does it mean the name of the folder in which the code lives? thx

**Comment by massi-ang** [comment]
Hi @andreprawira, 
here is an example of a valid remote: `s3://my-git-bucket/my-repo` where `my-repo` would be what I refer to as prefix. I would suggest you use a prefix matching then name of your repository and possibly share a bucket for multiple repositories.

This is an invalid remote `s3://my-git-bucket/` since it only uses the name of the bucket and does not have any prefix. 

For more information about Amazon S3 and prefixes, you can refer to https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-prefixes.html
